version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - JWT_KEY=$JWT_KEY
      - SESSIONS_SECRET=$SESSIONS_SECRET
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - '81:3000'
    depends_on:
      - db
    volumes:
      - 'node_modules:/home/node/app/node_modules'
    networks:
      - auth-network
  db:
    image: 'mongo:4.1.8-xenial'
    container_name: db
    env_file: .env
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - './data/db:/data/db'
    networks:
      - auth-network
networks:
  auth-network:
    driver: bridge
volumes:
  node_modules: null
